import { PrismaClient } from '@prisma/client';
import { syncSystemTasks } from './src/lib/task-sync';

const db = new PrismaClient();

async function testTasks() {
  console.log('--- TEST TASK SYNC LOGIC ---');
  
  const user = await db.user.findFirst();
  if (!user) {
    console.error('No users found in database to test with.');
    return;
  }
  const systemUserId = user.id;

  console.log('Run 1: Creating initial tasks...');
  const res1 = await syncSystemTasks(systemUserId);
  console.log('Result 1:', res1);

  console.log('\nRun 2: Verifying deduping (should be 0 creates)...');
  const res2 = await syncSystemTasks(systemUserId);
  console.log('Result 2:', res2);

  if (res2.creates > 0) {
    console.error('ERROR: Deduping failed, created tasks again!');
  } else {
    console.log('SUCCESS: Deduping works, no duplicates created.');
  }

  // Let's take an OPEN task and mark it DONE
  const openTask = await db.taskItem.findFirst({
    where: { status: 'OPEN', dedupeKey: { not: null } }
  });

  if (openTask) {
    console.log(`\nMarking task ${openTask.id} (${openTask.dedupeKey}) as DONE...`);
    await db.taskItem.update({
      where: { id: openTask.id },
      data: { status: 'DONE', resolvedAt: new Date(), resolvedById: null }
    });

    console.log('\nRun 3: Verifying reopen logic...');
    // Since the source condition hasn't changed, syncSystemTasks should reopen it
    const res3 = await syncSystemTasks(systemUserId);
    console.log('Result 3:', res3);
    
    if (res3.reopens > 0) {
      console.log('SUCCESS: Reopen logic works.');
      const taskLogs = await db.taskLog.findMany({
        where: { taskId: openTask.id, actionType: 'STATUS_CHANGED' }
      });
      console.log('Task Logs for reopened task:', taskLogs);
    } else {
      console.error('ERROR: Task was not reopened!');
    }
  } else {
    console.log('\nNo OPEN tasks generated by seed data to test reopen logic.');
  }

  console.log('\nTesting complete.');
}

testTasks().catch(console.error).finally(() => db.$disconnect());
